### ISSUE TITLE
set_effect() error

### ISSUE THREAD

**Issue by vadichi** [MylesMor/nanoleafapi#1]
There is an error in "set_effect()" function. 
Code:
```
    def set_effect(self, effect_name):
        ...
        data = {"select": effect}
```

The request is trying to be formed with an undeclared variable "effect" so the function call results in an error.
The right code would be:
```
    def set_effect(self, effect_name):
        ...
        data = {"select": effect_name}
```

**Comment by MylesMor** [comment]
Thanks, must have somehow missed that. I'll update the PyPi package later today.
