### ISSUE TITLE
Create Events: add examples in wiki

### ISSUE THREAD

**Issue by MatthewARoy** [MylesMor/nanoleafapi#3]
Hi, this is excellent! Very excited to use it.

How can you create new events with this? I see the register events.
Is it possible to set single panels to have an effect via that? Or is it just listening to active events.
Can you provide a more detailed example set for generating a new event in the wiki?

Thanks

**Comment by MylesMor** [comment]
Hi, I unfortunately don't think I did the best job with naming the methods. 

`register_event` will listen for all the event types you provide it in the second argument, including the state event and touch event (most common ones). Whenever one of these occur, it will send the contents of the event data (in a dictionary) to the function specified and created by you and given as a first argument. 

This means you can then use this data stored in the dictionary (or even the fact that the event occurred) to do anything else such as setting an effect, or even controlling other smart devices as I tried with the touch event. 

I hope this is what you meant, let me know if it needs any further explanation and I'll try to add a more detailed example soon, in fact I'll add an example code file with examples of all the functions in action.

**Comment by MatthewARoy** [comment]
Ok, so it's not possible to set nanoleaf states via the event states, this is more just listening?

**Comment by MylesMor** [comment]
I'm still not totally sure what you mean but as far as I know, all you can do is listen for events and then run code when they're found, which is what `register_event` does. 

There is a way to send an effect dictionary if that's what you mean, which basically creates a new effect using the parameters specified. This functionality isn't currently in my package but planning to add it in the next update.

**Comment by MatthewARoy** [comment]
I understand. Creating a new effect is what I was looking for, I'll look
into their SDK and look forward to your next update!

**Comment by MylesMor** [comment]
Great! In the mean time until my next update, have a look at section `3.2.4 Effects Commands` here: https://forum.nanoleaf.me/docs/openapi

It just gives some information if you would like to have a go at doing it yourself.

**Comment by MylesMor** [comment]
Commit 764c459cebc64dd020896c9affba3843afaeaa42 (version 1.1.5) adds a way to send these user-created effect dictionaries to the lights, using `write_effect(effect_dict)`. You still need to create the effect dictionary by hand, but I'm planning some features to make this a little easier in the future.

**Comment by MatthewARoy** [comment]
Thank you!
