### ISSUE TITLE
feedback -> type hinting mypy

### ISSUE THREAD

**Issue by Phuket2** [MylesMor/nanoleafapi#5]
Myles, just some info incase you are interested. I just started using mypy (playing really) and I was using nanoleafapi.  Mypy reports
'Skipping analyzing 'nanoleafapi': found module but no type hints or library stubs'
and gives the following note in the output.
note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
Anyway I read the info at the link, and it and it talks about a genstub tool that is installed with mypy that creates .pyi stub files for a package.  Anyway, I did 'genstub -p nanoleafapi' and it generated the stub files in a dir and mypy uses those stub files.   

Maybe this is old news to you.  Just seems like a nice simple way to put the toe in the water for type hinting. As well as the stub files which I was not aware of , seem nice so as not to pollute your source code.  

I also watch this https://youtu.be/hTrjTAPnA_k from PyCon 2019 which was helpful.  

Anyway, I am not suggesting you need this, just sharing my experience.

**Comment by MylesMor** [comment]
Thanks, I'll have a look into it!

**Comment by MylesMor** [comment]
Added type hinting and CI pipeline with a mypy test
