### ISSUE TITLE
Question: Are bulbs and strips supported?

### ISSUE THREAD

**Issue by redaxmedia** [MylesMor/nanoleafapi#9]
Hello,

I would like to know if this library supports the [Nanoleaf Essentials](http://nanoleaf.me/en-EU/products/?product=lighting-essentials&type=all) bulbs and strips aswell?

**Comment by MylesMor** [comment]
Hi, I don't own any of these devices yet as they seem to be permanently out of stock, so unfortunately I don't know and haven't been able to test with them. I would assume they follow a similar API for the basic functions but no guarantee yet. If I manage to get my hands on one I'll update you here but not sure when that will be. 

Sorry about that!

**Comment by redaxmedia** [comment]
@MylesMor Don't worry... I just ordered them on a German website and will give you an report as soon they arrive. Not sure you can buy from the UK [here](https://www.bauhaus.info/led-leuchtmittel/nanoleaf-smart-led-leuchtmittel-essential-light-bulb/p/27888782) Just in case this is not working, I have no problem to send you a bulb as a proxy.

You properly saw the linked project **Chroma Feedback** that properly will use this library - looking forward to it.

**Comment by MylesMor** [comment]
Thanks for the link but unfortunately from what I can see they don't seem to ship to the UK. Let me know how it goes when you get your bulb and if there are issues then I might take up your offer of you acting as a proxy if the shipping to the UK isn't too expensive, thank you! 

Your project looks great! Would you just be using the basic power/brightness/colour functionality?  I hope the API would be the same for those functions, but we'll see.

**Comment by redaxmedia** [comment]
That being said, thanks a lot for you project aswell. I will reach out to you and send you my bulb just in case the library is not working with it. Let's keep this issue open as an reminder.

**Comment by redaxmedia** [comment]
@MylesMor 

Finally got the bulbs in my hands but I had to figure out these are Bluetooth only or need a hub like the Apple HomePod Mini? The first bulb that does not work like the others, it is a shame.

Whatsoever, I wonder if this bulb is getting an IP even when it is connected to an hub. What are your thoughts?

**Comment by MylesMor** [comment]
I can't quite remember exactly the setup process for my panels, but I think they broadcast their own WiFi network, you connect to that and send input the details for your home network. They then connect to your home network and are then assigned an IP. I assumed the bulb would have a similar process?

**Comment by redaxmedia** [comment]
Oh well, I was hoping for that process but as it turns out new technology comes into play. After searching for it, the Bluetooth is just a fallback and these bulbs are using the new "Thread" standard that is like a decentralized mesh network. The Apple HomePod Mini is like one of the first devices that supports "Thread" and works like a portal to other devices.

The other standard is "Zigbee" and the old nanoleaf devices properly use that one instead!?

**Comment by MylesMor** [comment]
Is there no other way to set them up and use them? I didn't require any hub or anything for my light panels...

**Comment by redaxmedia** [comment]
The only way to connect to that "Thread" network is an border router like the Apple HomePod Mini. I am not sure how this works but I guess it does some kind of IP mapping to make each device public.

**Comment by MylesMor** [comment]
I'm not sure I'm understanding this correctly... Does it have to use the new "Thread" network though? I thought it could just connect to a normal WiFi network like the old panels? You're setting it up with the Nanoleaf app right?

**Comment by redaxmedia** [comment]
I used the Nanoleaf app and have a connection to the bulb as long my Bluetooth is enabled. There is no option to enter a wifi because the bulb is creating it's own - that is the "Thread" what I am talking about. If you have like 4 bulbs they create a mesh and therfore bigger "Thread" network. Somehow we are looked out ... I can send the bulb to you but without a border router (was is also just guessing) you cannot access the bulb.

**Comment by redaxmedia** [comment]
Closing this issue for the moment - I send the bulb back and plan to buy a proper nanoleaf and send it back also... haha

**Comment by MylesMor** [comment]
Ah, I understand now, thanks. Unfortunately, my library obviously won't work with Bluetooth, it's just based on the HTTP requests and even with the router I'm not sure it would work as you said. Good plan, to be honest, the majority of people with Nanoleaf devices will have the light panels anyway at this point, if you need any help with implementing it when you get the panels, give me a shout. Sorry about that!

**Comment by redaxmedia** [comment]
@MylesMor I'll reach out to you for testing it. Thanks man
